language: php

php:
  - 7.1

before_script:
  - composer self-update
  - composer install
  - cp phpunit.xml.dist phpunit.xml
  - cp app/config/parameters.yml.dist app/config/parameters.yml

script:
  - vendor/phpunit/phpunit/phpunit --testsuite=unit
  - vendor/phpunit/phpunit/phpunit --testsuite=integration
  - vendor/phpunit/phpunit/phpunit
