# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # we need this because of unit testing, you can override this setting on individual services
        public: true

    AppBundle\Date\DecadeCalculator:
        public: true

    AppBundle\Library\Book\Repository\BookRepository:
        public: true

    AppBundle\Library\LibraryStatistics:
        public: true

    AppBundle\Number\AverageCalculator:
        public: true

    AppBundle\Test\UglyTestCommand:

    AppBundle\Test\TestCommand:

    Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder:
        arguments:
            $cost: 4
